development:
  cloud_name: iaw2015
  api_key: '399659993567734'
  api_secret: xIZu94rm2hSbjcobVcBovVro3uo
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: iaw2015
  api_key: '399659993567734'
  api_secret: xIZu94rm2hSbjcobVcBovVro3uo
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: iaw2015
  api_key: '399659993567734'
  api_secret: xIZu94rm2hSbjcobVcBovVro3uo
  enhance_image_tag: true
  static_image_support: false
